Feature reviews structures
Spoilers-TN/Bookfinder pull request #11
Opened 2023-02-25 10:08 UTC by KevinVargas0510

Added functions to update and delete reviews

2023-02-25 11:00 UTC, francescomasala approved these changes
Codice coerente con le linee guida di bookfinder e kotlin

2023-02-25 11:07 UTC, bertigiacomo commented
Codice non funzionante, da rivedere assoulutamente @sidkAmar @Bleggio15

2023-02-25 11:07 UTC, francescomasala commented
@sidkAmar @Bleggio15 Segnalo errore in CI:
`> Task :compileKotlin
e: /home/runner/work/Bookfinder-Kotlin/Bookfinder-Kotlin/src/main/kotlin/it/tn/spoilers/database/services/ReviewsService.kt: (35, 27): Unresolved reference: deleteOneById`


`e: /home/runner/work/Bookfinder-Kotlin/Bookfinder-Kotlin/src/main/kotlin/it/tn/spoilers/database/services/ReviewsService.kt: (42, 27): Unresolved reference: deleteOneById`

2023-02-26 21:18 UTC, francescomasala requested changes

2023-02-26 21:18 UTC, francescomasala commented on src/main/kotlin/it/tn/spoilers/database/services/ReviewsService.kt
> +        reviewsCollection.deleteOneById(oldReview.Review_ID)
Manca il metodo `reviewsCollection.deleteOneById()` all'interno della classe

2023-02-26 21:18 UTC, francescomasala commented on src/main/kotlin/it/tn/spoilers/database/services/ReviewsService.kt
> +        reviewsCollection.deleteOneById(review.Review_ID)
Manca il metodo `reviewsCollection.deleteOneById()` all'interno della classe

2023-05-12 09:46 UTC, closed without merging